"""Added a relationship between the user and the pitches

Revision ID: 120de4173978
Revises: a972336c445b
Create Date: 2022-02-08 18:12:14.171256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120de4173978'
down_revision = 'a972336c445b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitches_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'pitches', ['pitches_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'pitches_id')
    # ### end Alembic commands ###
