""" Changes

Revision ID: a972336c445b
Revises: d8080607604f
Create Date: 2022-02-07 22:19:25.425387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a972336c445b'
down_revision = 'd8080607604f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitchwords', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('vote', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categorys.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pitches ')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches ',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"pitches _id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('pitchwords', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('vote', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categorys.id'], name='pitches _category_id_fkey'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='pitches _comment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pitches _pkey')
    )
    op.drop_table('pitches')
    # ### end Alembic commands ###
