"""Added a password column to Users

Revision ID: d70604903e79
Revises: 75c9b749664b
Create Date: 2022-02-07 01:26:09.021590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70604903e79'
down_revision = '75c9b749664b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['username'])
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
